change_mode:
  name: Change Mode
  description: Change the operating mode of a Leakomatic device.
  target:
    entity:
      domain: leakomatic
      integration: leakomatic
  fields:
    mode:
      name: Mode
      description: The new mode to set for the device.
      required: true
      selector:
        select:
          options:
            - label: Home
              value: home
            - label: Away
              value: away
            - label: Pause
              value: pause 